name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  web-deploy:

    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ftp.partnerinaja.com
        username: appsent@appsent.partnerinaja.com
        password: ${{ secrets.appsent_password }}

  # laravel-deploy:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
  #     with:
  #       php-version: '8.0'
  #   - uses: actions/checkout@v3
  #   - name: Install Dependencies
  #     run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  #   - name: Generate key
  #     run: php artisan key:generate
  #   - name: Directory Permissions
  #     run: chmod -R 777 storage bootstrap/cache